FROM python

RUN mkdir pipelines

WORKDIR pipelines

COPY ./ ./

RUN pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r test_requirements.txt

RUN pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt

CMD ["pytest"]